<a href="https://colab.research.google.com/github/Ashi743/pytorch/blob/main/pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
## pytorch fundamental
import numpy as np

import torch
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
print(torch.__version__)


2.5.0+cu121


In [4]:
#tenosrs
## scalar
scalar = torch.tensor(7)
print(scalar.shape)
scalar.ndim

torch.Size([])


0

In [5]:
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7,7])
print(vector.ndim)
print(vector.shape)
print(vector.ndim)

1
torch.Size([2])
1


In [7]:
#matrix
MATRIX= torch.tensor(([[7,8],
                      [1,9]]))

print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX.dtype)
print(MATRIX.device)
print(MATRIX)
print(MATRIX[1])
print(MATRIX[1][1])

2
torch.Size([2, 2])
torch.int64
cpu
tensor([[7, 8],
        [1, 9]])
tensor([1, 9])
tensor(9)


In [8]:
#TENSOR
TENSOR=   torch.tensor([[[1,2,3],
                         [4,5,6],
                         [7,8,9]]])
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR.dtype)
print(TENSOR.device)
print(TENSOR)
print(TENSOR[0])
print(TENSOR[0][1])
print(TENSOR[0][1][1])


3
torch.Size([1, 3, 3])
torch.int64
cpu
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([4, 5, 6])
tensor(5)


In [9]:
TENSOR=   torch.tensor([[[[1,1,2],
                         [2,1,1],
                         [3,1,1]],[[1,2,3],
                         [4,5,6],
                         [7,8,9]]]])
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR.dtype)
print(TENSOR.device)
print(TENSOR)
print(TENSOR[0])
print(TENSOR[0][1])
print(TENSOR[0][1][1])


4
torch.Size([1, 2, 3, 3])
torch.int64
cpu
tensor([[[[1, 1, 2],
          [2, 1, 1],
          [3, 1, 1]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])
tensor([[[1, 1, 2],
         [2, 1, 1],
         [3, 1, 1]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([4, 5, 6])


In [10]:
#random tensor
random_tensor= torch.rand(3,4,2)
print(random_tensor.ndim)
print(random_tensor.shape)
print(random_tensor.dtype)
print(random_tensor.device)
print(random_tensor)
print(random_tensor.requires_grad)

3
torch.Size([3, 4, 2])
torch.float32
cpu
tensor([[[0.8724, 0.8424],
         [0.2814, 0.2154],
         [0.9205, 0.2762],
         [0.7627, 0.7805]],

        [[0.5021, 0.0062],
         [0.2108, 0.1160],
         [0.2819, 0.6068],
         [0.5742, 0.4618]],

        [[0.2313, 0.8577],
         [0.1561, 0.1528],
         [0.1071, 0.3067],
         [0.0588, 0.1264]]])
False


In [11]:
#create random tensor with similar shape as of image tensor
#rgb
random_image_size_tensor= torch.rand(size= (224,224,3)) #size is a param
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [12]:
#zeros and ones
print(np.zeros((3,4)))
zeros= torch.zeros(size=(3,4))
print(zeros.type())
random_tensor =torch.rand(size=(3,4))
zeros*random_tensor

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
torch.FloatTensor


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
ones= torch.ones(size=(3,4))
ones.dtype

torch.float32

In [14]:
#creating a range of tensors and tensors- like
one_to_12= torch.arange(start=1, step=2 ,end=12)
one_to_12

tensor([ 1,  3,  5,  7,  9, 11])

In [15]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [16]:
zeroos= torch.zeros_like(input=one_to_12)
zeroos

tensor([0, 0, 0, 0, 0, 0])

In [17]:
# float 32 tensor
float_32_tensor= torch.tensor([3.0,4.0,5.0,6], dtype= torch.float64,   # what dtype float 32 or 64
                              device= "cpu",         #what divice tensor on
                              requires_grad= False)  #to track gradient or not


In [18]:
#change type
float_32_tensor.dtype
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [19]:
float_32_tensor*float_16_tensor    #max(16,64)

tensor([ 9., 16., 25., 36.], dtype=torch.float64)

In [20]:
#getting tensor attributes
int_32_tensor= torch.tensor([3,4,5,6] ,dtype= torch.int32)
print(int_32_tensor.dtype)
print(int_32_tensor.shape)
print(int_32_tensor.device)

torch.int32
torch.Size([4])
cpu


In [21]:
res1= float_16_tensor*int_32_tensor
res1.dtype
memory_used = float_32_tensor.element_size() * float_32_tensor.numel()
memory_used

32

In [22]:
float_32_tensor.element_size()

8

In [23]:
#getting info
print(res1.shape)
print(res1.dtype)
print(res1.device)

torch.Size([4])
torch.float16
cpu


In [24]:
#manipulating tensors(tensor operations)
#addition
tensor= torch.tensor([1,2,3])

print(tensor+10)
#subtraction
print(tensor-10)
#multiplication
print(tensor*10)
#division
print(tensor/10)

print()

print(torch.mul(tensor,10))
print(torch.add(tensor,10))
print(torch.sub(tensor,10))
print(torch.div(tensor,10))


tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


In [25]:
### matrix multiplication
# element-wise
# matrix or dot product

print(tensor * tensor)


tensor([1, 4, 9])


In [26]:
tensor= torch.tensor([10,20,30,40,50,60,7,8,9])


In [27]:
%%time
val= 0
for i in range(len(tensor)):
  val+=tensor[i]*tensor[i]

val

CPU times: user 568 µs, sys: 87 µs, total: 655 µs
Wall time: 1.97 ms


tensor(9294)

In [28]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 0 ns, sys: 698 µs, total: 698 µs
Wall time: 9.79 ms


tensor(9294)

In [29]:
###error in DL is shape error
#1. inner dim must match
#2. output is shape of outer dim   DUHH!!

print(torch.matmul(torch.rand(3,2), torch.rand(2,3)))
torch.matmul(torch.rand(2,3).T, torch.rand(2,3))


tensor([[0.0847, 0.8448, 0.4068],
        [0.4567, 0.5882, 0.6364],
        [0.0605, 0.7831, 0.3610]])


tensor([[0.1036, 0.1066, 0.0122],
        [0.8090, 0.7396, 0.2790],
        [0.7096, 0.7108, 0.1222]])

In [30]:
tensor_A= torch.tensor([[1,2],
                     [3,4],
                     [5,6]])
tensor_B= torch.tensor([[7,10],
                     [8,11],
                     [9,12]])

torch.mm(tensor_A, tensor_B.T)      # torch.mm==torch.matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [31]:
#min, max,avg,sum
x= torch.arange(1,100,10)
print(x)
print(x.min())
print(x.max())
print(x.type(torch.float32).mean())
print(x.sum())
torch.mean(x, dtype=torch.float32)

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
tensor(1)
tensor(91)
tensor(46.)
tensor(460)


tensor(46.)

In [32]:
#finding positional min max
print(x.argmin())
print(x.argmax())         #SOFTMAX USED LATER
x[0] ,x[9]

tensor(0)
tensor(9)


(tensor(1), tensor(91))

## Reshaping, stacking, squeezing, unsqueezing
* reshape to defined shape
* view the tensor of certain shape keeping memory same as original
* stackin horiz or vertically
* squeeze all 1 dim out from tensor
* unsqueeze in a 1 dim into the tensor
* permute the input to other view in a certain way

In [33]:
#reshape, stacking, squeezing, unsqueezing
import torch
x = torch.arange(1. ,13.)
print(x)
x.shape

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


torch.Size([12])

In [34]:
print(x.reshape(4,3))
print(x.reshape(3,4).shape)

print()
#change view
z= x.view(4,3)
print(z, z.shape)

print()
#stack
print(torch.stack([x,x,x,x], dim=0))  # along column, row stack
print(torch.vstack([x,x,x,x]))
v_stack =torch.vstack([x,x,x,x])
print()
print(torch.stack([x,x,x,x], dim=1))  # along row, column stack

print(torch.hstack([x,x,x,x]))


tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([3, 4])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]]) torch.Size([4, 3])

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  

In [35]:
#squeeze
v_ = torch.tensor([[1,2,3]])
print(v_.squeeze())
print(v_.squeeze().shape)
v_.squeeze()

tensor([1, 2, 3])
torch.Size([3])


tensor([1, 2, 3])

In [36]:
torch.unsqueeze(v_, dim=0)

tensor([[[1, 2, 3]]])

In [37]:
x_original= torch.rand(size=(224,225,3))  #height ,width, colour
x_original.shape
x_permuted= x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 225])

In [38]:
x_original[0,0,0]=123

In [39]:
import torch
x= torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [47]:
#indexing
x[0][0]
x[:, :, 0]
x[:, 1, 1]
x[0, 0, :]

tensor([1, 2, 3])

In [50]:
x[:,1,1]==x[0][1][1]

tensor([True])

In [52]:
x[:,:,2]

tensor([[3, 6, 9]])

Pytorch and numpy

In [58]:
# torch to numpy torch.Tensor.numpy
# numpy to torch torch.from_numpy(ndarray)  --> reflects numpy float64(defalut)
import torch, numpy as np
array= np.arange(1.0, 8.0)
tensor= torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [57]:
array.dtype ,tensor.dtype, torch.arange(1.0, 8.0).dtype

(dtype('float64'), torch.float64, torch.float32)

In [61]:
array+=1
array

array([ 4.,  5.,  6.,  7.,  8.,  9., 10.])

In [62]:
tensor= torch.ones(7)
numpy_tensor= tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [63]:
tensor+=1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

In [64]:
### reproducibility  (trying out random out of random)

In [72]:
# random no. --> tensor application --. update-->
torch.rand(3,3,3)
# to reduce teh randomness     WE USE RANDOM SEED  so as to flavour the randomness
RANDOM_SEED= 42
torch.manual_seed(RANDOM_SEED)
a= torch.rand(3,3,3)

RANDOM_SEED= 42
torch.manual_seed(RANDOM_SEED)  #just for one vlock of code or each
b= torch.rand(3,3,3)
print(a)
print(b)
print(a==b)

tensor([[[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]],

        [[0.1332, 0.9346, 0.5936],
         [0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739]],

        [[0.2666, 0.6274, 0.2696],
         [0.4414, 0.2969, 0.8317],
         [0.1053, 0.2695, 0.3588]]])
tensor([[[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]],

        [[0.1332, 0.9346, 0.5936],
         [0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739]],

        [[0.2666, 0.6274, 0.2696],
         [0.4414, 0.2969, 0.8317],
         [0.1053, 0.2695, 0.3588]]])
tensor([[[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]]])


In [1]:
#running on GPU's
!nvidia-smi

Sat Nov  2 06:24:20 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
torch.cuda.is_available()

False

In [3]:
#setup device agnostic
device= 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [2]:
import torch

# Set the seed for CPU
torch.manual_seed(42)

# Set the seed for all GPUs
torch.cuda.manual_seed_all(42)
tensor = torch.rand(3, 4)
tensor, tensor.device

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 device(type='cpu'))

In [2]:
import torch

# Set the seed for reproducibility
torch.manual_seed(7)

# Create a random tensor with shape (1, 1, 1, 10)
tensor = torch.rand((1, 1, 1, 10))

# Remove all dimensions of size 1
tensor_squeezed = tensor.squeeze()

# Print the original tensor and its shape
print("Original Tensor:", tensor)
print("Original Shape:", tensor.shape)
print()
# Print the squeezed tensor and its shape
print("Squeezed Tensor:", tensor_squeezed)
print("Squeezed Shape:", tensor_squeezed.shape)

Original Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Original Shape: torch.Size([1, 1, 1, 10])

Squeezed Tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Squeezed Shape: torch.Size([10])
