<a href="https://colab.research.google.com/github/Ashi743/pytorch/blob/main/pytorch_tensor_campusx_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [3]:
if torch.cuda.is_available():
    print('GPU')
    print(torch.cuda.get_device_name(0))
else:
    print('CPU')

CPU


In [5]:
#creating tensors
a= torch.empty(2,3)    #its just a space their random
type(a)

torch.Tensor

In [9]:
print(torch.zeros(2,3))
print()
print(torch.ones(2,3))
print()
print(torch.rand(2,3))
print()
print(torch.randn(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247]])

tensor([[-1.5228,  0.3817, -1.0276],
        [-0.5631, -0.8923, -0.0583]])


In [8]:
print(torch.manual_seed(1))
print(torch.rand(2,3))

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])


In [10]:
torch.tensor( [ [1,2,3], [4,5,6] ])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
print(torch.arange(1,10,2))
print()
print(torch.linspace(1,10,5))
print()
print(torch.logspace(1,10,5))
print()
print(torch.eye(3))     #identity matrix
print()
print(torch.full((3,2), 5))

tensor([1, 3, 5, 7, 9])

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

tensor([1.0000e+01, 1.7783e+03, 3.1623e+05, 5.6234e+07, 1.0000e+10])

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

tensor([[5, 5],
        [5, 5],
        [5, 5]])


Tensor shapes

In [15]:
x= torch.tensor( [ [1,2,3], [4,5,6] ])
print(x)
print(x.shape)
print(x.size())

torch.empty_like(x)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.Size([2, 3])


tensor([[133007896358480,  99135393581168,    489626271855],
        [   446676598883,    498216206382,    472446402661]])

In [14]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.rand_like(x , dtype=torch.float32)

tensor([[0.3398, 0.5239, 0.7981],
        [0.7718, 0.0112, 0.8100]])

Tensor data type


In [17]:
x.dtype

torch.int64

In [18]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

mathematical operations

In [23]:
x+2
(x*100) //3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [24]:
((x*100) //3 )%2

tensor([[1, 0, 0],
        [1, 0, 0]])

In [27]:
#absolute
c= torch.tensor([1.2,-2.4,3.6])
torch.abs(c)

tensor([1.2000, 2.4000, 3.6000])

In [30]:
print(torch.round(c))
print(torch.ceil(c))
print(torch.floor(c))
print(torch.trunc(c))
print(torch.frac(c))
torch.clamp(c ,min=-1.0, max=2.0)


tensor([ 1., -2.,  4.])
tensor([ 2., -2.,  4.])
tensor([ 1., -3.,  3.])
tensor([ 1., -2.,  3.])
tensor([ 0.2000, -0.4000,  0.6000])


tensor([ 1.2000, -1.0000,  2.0000])

In [33]:
e =torch.randint(size =(3,2), low= 0, high= 10, dtype=torch.float32)
e


tensor([[3., 6.],
        [2., 0.],
        [5., 9.]])

In [37]:
print(torch.sum(e))
print(torch.sum(e, dim=0)) #columns wise
print(torch.sum(e, dim=1)) #row wise

print(torch.mean(e))
print(torch.mean(e, dim=0)) #columns wise
print(torch.mean(e, dim=1)) #row wise

print(torch.std(e))


tensor(25.)
tensor([10., 15.])
tensor([ 9.,  2., 14.])
tensor(4.1667)
tensor([3.3333, 5.0000])
tensor([4.5000, 1.0000, 7.0000])
tensor(3.1885)


In [40]:
print(torch.median(e))
print(torch.max(e) ,torch.min(e))
print(torch.prod(e) ,torch.prod(e, dim=0)) #columns wise
print(torch.prod(e, dim=1)) #row wise

tensor(3.)
tensor(9.) tensor(0.)
tensor(0.) tensor([30.,  0.])
tensor([18.,  0., 45.])


In [41]:
print(torch.var(e))

print(torch.argmax(e))

print(torch.argmin(e))

tensor(10.1667)
tensor(5)
tensor(3)


In [42]:
f= torch.randint(size =(3,2), low= 0, high= 10, dtype=torch.float32)
g= torch.randint(size =(2,3), low= 0, high= 10, dtype=torch.float32)
print(f)
print(g)

tensor([[5., 3.],
        [3., 5.],
        [8., 9.]])
tensor([[1., 4., 4.],
        [5., 8., 0.]])


In [45]:
print(torch.matmul(f,g))
print(torch.mm(f,g))

tensor([[ 20.,  44.,  20.],
        [ 28.,  52.,  12.],
        [ 53., 104.,  32.]])
tensor([[ 20.,  44.,  20.],
        [ 28.,  52.,  12.],
        [ 53., 104.,  32.]])


In [46]:
vector1= torch.tensor([1,2,3])
vector2= torch.tensor([4,5,6])
print(torch.dot(vector1,vector2))

tensor(32)


In [47]:
h =torch.randint(size =(3,2), low= 0, high= 10, dtype=torch.float32)
print(h)
print(h.T)

tensor([[1., 3.],
        [1., 4.],
        [7., 8.]])
tensor([[1., 1., 7.],
        [3., 4., 8.]])


In [50]:
torch.transpose(h,0,1)

tensor([[1., 1., 7.],
        [3., 4., 8.]])

In [53]:
print(torch.det(e))
print(torch.inverse(h))
print(torch.eig(h))
print(torch.svd(h))

RuntimeError: linalg.det: A must be batches of square matrices, but they are 3 by 2 matrices

In [55]:
m= torch.rand(2,3)
n= torch.rand(2,3)

In [56]:
m.add_(n)

tensor([[0.6671, 1.3978, 0.9241],
        [1.0886, 0.9917, 0.8005]])

In [57]:
torch.relu(m)

tensor([[0.6671, 1.3978, 0.9241],
        [1.0886, 0.9917, 0.8005]])

In [58]:
m.relu_ #_ leads to inplace

<function Tensor.relu_>

copying

In [ ]:
#assignment
#  b=a
#id(a)= id(b)

#b= a.clone(a)


In [60]:
#reshape
print(m.reshape(3,2))
print(m.flatten())

tensor([[0.6671, 1.3978],
        [0.9241, 1.0886],
        [0.9917, 0.8005]])
tensor([0.6671, 1.3978, 0.9241, 1.0886, 0.9917, 0.8005])


In [61]:
b =torch.rand(2,3,4)
b

tensor([[[0.7442, 0.5285, 0.6642, 0.6099],
         [0.6818, 0.7479, 0.0369, 0.7517],
         [0.1484, 0.1227, 0.5304, 0.4148]],

        [[0.7937, 0.2104, 0.0555, 0.8639],
         [0.4259, 0.7812, 0.6607, 0.1251],
         [0.6004, 0.6201, 0.1652, 0.2628]]])

In [63]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [64]:
#unsqueeze
c =torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [66]:
c.unsqueeze(1).shape   #adds dims

torch.Size([226, 1, 226, 3])

In [67]:
#squeeze
c.squeeze(0).shape

torch.Size([226, 226, 3])